@host = http://localhost:5106

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1MGU1NjNlNy0xZDZlLTQ3OTYtYjkzZi0yNzE2NjMzMmRmNGIiLCJnaXZlbl9uYW1lIjoiRHVjIiwiZmFtaWx5X25hbWUiOiJWdSIsImp0aSI6IjEzOTZiYWViLWYyNmEtNGRiNy04ZjVkLTUzNmQ3NTQxOTFhZCIsImV4cCI6MTc0OTM1OTI5MiwiaXNzIjoiUG9rZW1vbkFwaSIsImF1ZCI6IlBva2Vtb25BcGkifQ.f9PrfMaxkaE5lAkXvEmnAloy1h-uWFeaKyMqYQiDV6g