@host=http://localhost:5106
@hostId=1
@bearerToken="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1MGU1NjNlNy0xZDZlLTQ3OTYtYjkzZi0yNzE2NjMzMmRmNGIiLCJnaXZlbl9uYW1lIjoiRHVjIiwiZmFtaWx5X25hbWUiOiJWdSIsImp0aSI6IjEzOTZiYWViLWYyNmEtNGRiNy04ZjVkLTUzNmQ3NTQxOTFhZCIsImV4cCI6MTc0OTM1OTI5MiwiaXNzIjoiUG9rZW1vbkFwaSIsImF1ZCI6IlBva2Vtb25BcGkifQ.f9PrfMaxkaE5lAkXvEmnAloy1h-uWFeaKyMqYQiDV6g"



POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{bearerToken}}

{
    "name": "YummyMenu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}